### ISSUE TITLE
User story - View a list of products

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#1]
**EPIC:** 
View a list of products

**User story:**
In order to **select an item to purchase** as a **user**, I can **have access to a list of products**

**Acceptance Criteria:**
When a user clicks on menu products, they can see a list of products

**Tasks:**

- [x] Create a Json file for products
- [x] Create an app for products
- [x] Create a view for products
- [x] Create a model for products
- [x] Create a template for products
- [x] Create URLs for products
