### ISSUE TITLE
User story - Adjust the quantity of individual items in my bag

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#10]
**EPIC:** 
Adjust the quantity of individual items in my bag

**User story:**
In order to **easily make changes to my purchase before checkout** as a **user**, I can **adjust the quantity of individual items in my bag**

**Acceptance Criteria:**
When a user clicks on minus and plus icon, they can update the items to add more or less quantity of the same product or remove it entirely.

**Tasks:**

- [x] Create a view for update item
- [x] Create a form for update item
- [x] Create a Javascript for update item
