### ISSUE TITLE
User story - Easily enter my payment information

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#11]
**EPIC:** 
Easily enter my payment information

**User story:**
In order to **checkout quickly and with no hassles** as a **user**, I can **easily enter my payment information**

**Acceptance Criteria:**
When user is checking out, they can add their card details.

**Tasks:**

- [x] Create an Stripe account
- [x] Set up Stripe elements
- [x] Update checkout view with stripe parameters
