### ISSUE TITLE
User story - View an order confirmation after checkout

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#12]
**EPIC:** 
View an order confirmation after checkout

**User story:**
In order to **verify that I haven't made any mistakes** as a **user**, I can **view an order confirmation after checkout**

**Acceptance Criteria:**
When a user click on their profile menu, they can see an order history with all the datails.

**Tasks:**

- [x] Create a table for order history
- [x] Create a view for order history
- [x] Create a template for checkout success
