### ISSUE TITLE
User story - Add new products

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#13]
**EPIC:** 
Add new products

**User story:**
In order to **add new items to my store** as an **admin**, I can **have access to add a new product**

**Acceptance Criteria:**
The admin can add new products.

**Tasks:**

- [x] Create a form for products
- [x] Create a view for add new product
- [x] Create a template for add new product
