### ISSUE TITLE
User story - Sort products by price

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#17]
**EPIC:** 
Sort products by price

**User story:**
In order to **find a product with the best price** as a **user**, I can **view a sorted list of products by price**

**Acceptance Criteria:**
The user can sort products by price.

**Tasks:**

- [x] Create a Django filter
- [x] Add parametera on products view
- [x] Create a Javascript function
