### ISSUE TITLE
User story - Checkout products

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#18]
**EPIC: **
Checkout products

**USER STORY:**
In order to **buy the products in my bag** as a **user**, I can **checkout with my address and pay for the items**

**ACCEPTANCE CRITERIA:**
The user can add his address and add payment details to finish transaction.

**TASKS:**

- [x] Create an app for checkout
- [x] Create a view for checkout
- [x] Create a model for checkout
- [x] Create a template for checkout
- [x] Create a form for checkout
- [x] Create URLs for checkout
