### ISSUE TITLE
User story - Wish list

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#21]
**EPIC:** 
Wish list

**User story:**
In order to **buy later a product that I liked** as a **user**, I can **save it to my favorites products in a wish list**

**Acceptance Criteria:**
As the user click to save an item, it will be displayed in a wishlist on the user profile.

**Tasks:**

- [x] Add an extra model inside Product's model
- [x] Create a template for wishlist
- [x] Add a view on products view
