### ISSUE TITLE
User story - Contact us

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#22]
**EPIC:** 
Contact us

**User story:**
In order to **get more information about my product's order or any problems that I have with the website** as a **user**, I can **submit a form with these queries**

**Acceptance Criteria:**
As the user click Contact Us page, they will be able to see Customer Care opening hours, Frequently asked questions, and a form that they can write any queries. When submited they will see a confirmation page with the estimated time of response.

**Tasks:**

- [x] Create a model for contact us
- [x] Create a template for contact us
- [x] Create a view for contact us
- [x] Create a form for contact us
