### ISSUE TITLE
User story - Review product

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#23]
**EPIC:** 
Review product

**User story:**
In order to **know the review of other people** as a **user**, I can **rate the products**

**Acceptance Criteria:**
As the user click the rating option and add a comment, they will be able to see all the reviews of the product selected.

**Tasks:**

- [x] Create a model inside Product's model
- [x] Create a form inside view_product template
- [x] Add an extra parameter inside view_product's view
- [x] Create a new parameter inside all_products view to calculate the reviews
- [x] Add the rating total to each product
