### ISSUE TITLE
User story - Have a personalized user profile

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#7]
**EPIC:** 
Have a personalized user profile

**User story:**
In order to **view my personal order history, order confirmation and save my delivery information** as a **user**, I can **have a personalized user profile**

**Acceptance Criteria:**
When a user clicks on "my profile", they can see order history and check or update default delivery information.

**Tasks:**

- [x] Create a form for profile
- [x] Create a template for profile
- [x] Create a model for profile and update profile
- [x] Create a view for profile and order history
