### ISSUE TITLE
User story - View items in my bag to be purchased

### ISSUE THREAD

**Issue by Adriele-lima** [Adriele-lima/Gifts-and-Flowers#9]
**EPIC:** 
View items in my bag to be purchased

**User story:**
In order to **identify the total cost of my purchase and all items** as a **user**, I can **view items in my bag to be purchased**

**Acceptance Criteria:**
When a user clicks in the bag icon, they can see their list of products to be purchased.

**Tasks:**

- [x] Create an app for bag
- [x] Create a view for bag
- [x] Create a model for bag
- [x] Create a template for bag
- [x] Create URLs for bag
